INSERT INTO categories (label) VALUES('');
INSERT INTO categories (label) VALUES('Abonnements');
INSERT INTO categories (label) VALUES('Assurance Crédit');
INSERT INTO categories (label) VALUES('Assurance Habitation');
INSERT INTO categories (label) VALUES('Assurance Suzuki');
INSERT INTO categories (label) VALUES('Assurance-vie');
INSERT INTO categories (label) VALUES('Carburant');
INSERT INTO categories (label) VALUES('Courses');
INSERT INTO categories (label) VALUES('Crédit Immobilier');
INSERT INTO categories (label) VALUES('Crédit Moto');
INSERT INTO categories (label) VALUES('Divers');
INSERT INTO categories (label) VALUES('École');
INSERT INTO categories (label) VALUES('EDF');
INSERT INTO categories (label) VALUES('Éparge TDM');
INSERT INTO categories (label) VALUES('Fast-Food');
INSERT INTO categories (label) VALUES('Finance');
INSERT INTO categories (label) VALUES('Frais Bancaires');
INSERT INTO categories (label) VALUES('Inconnu');
INSERT INTO categories (label) VALUES('Loisirs');
INSERT INTO categories (label) VALUES('Péage');
INSERT INTO categories (label) VALUES('Provisions');
INSERT INTO categories (label) VALUES('Régularisation Solde');
INSERT INTO categories (label) VALUES('Restaurants');
INSERT INTO categories (label) VALUES('Retraits');
INSERT INTO categories (label) VALUES('Revenus');
INSERT INTO categories (label) VALUES('Santé');
INSERT INTO categories (label) VALUES('Shopping');
INSERT INTO categories (label) VALUES('Stationnement');
INSERT INTO categories (label) VALUES('Syndic');
INSERT INTO categories (label) VALUES('Virements Externes');
INSERT INTO categories (label) VALUES('Voyages - Rome');